const Events = {
    UpdateHeader: 'updateHeader',
    ChangePath: 'changePath',
    Register: 'acceptRegistration',
    LoginSubmit: 'loginSubmit',
    LoginFieldFill: 'loginFieldFill',
    RegisterFieldFill: 'registerFieldFill',
    RegisterSubmit: 'registerSubmit',
    RefreshPage: 'refreshPage',
    UploadAvatar: 'uploadAvatar',
    ScrollToBlock: 'scrollToBlock',
    Logout: 'logout',
    ProfileEditFieldFill: 'profileFieldFill',
    ProfileEditSubmit: 'profileEditSubmit',
    TicketSelect: 'ticketSelect',
    TicketsBuy: 'ticketsBuy',
    MovieRate: 'movieRate',
    SubmitFilter: 'submitFilter',
    UpdateMovieList: 'updateMovieList',
    UpdateSchedule: 'updateSchedule',
    SubmitReply: 'submitReply',
    UpdateReply: 'updateReply',
    DropProfileNavigation: 'dropProfileNavigation',
    ScrollSlider: 'slideMovie',
    PaymentFieldFill: 'paymentFieldFill',
    PaymentSubmit: 'paymentSubmit',
    PaymentCrypto: 'paymentCrypto',
    PaymentOnline: 'paymentOnline',
    EditReply: 'editReply',
};

export default Events;
