const ExtractedFields = {
    CinemaData: new Set([
        'Address',
        'AuthorID',
        'HallCount',
        'ID',
        'Name',
        'PathToAvatar',
    ]),
    HallData: new Set([
        'id',
        'placeAmount',
        'placeConfig',
    ]),
    MovieData: new Set([
        'ActorList',
        'AgeGroup',
        'Country',
        'Description',
        'Duration',
        'GenreList',
        'ID',
        'Name',
        'PathToAvatar',
        'PathToSliderAvatar',
        'PersonalRating',
        'Producer',
        'Rating',
        'RatingCount',
        'ReleaseYear',
    ]),
    ProfileData: new Set([
        'login',
        'name',
        'surname',
        'pathToAvatar',
    ]),
    ReplyData: new Set([
        'ID',
        'MovieID',
        'Text',
        'User',
        'UserRating',
    ]),
    ScheduleData: new Set([
        'CinemaID',
        'Cost',
        'HallID',
        'ID',
        'MovieID',
        'PremierTime',
    ]),
    SettingsFormData: new Set([
        'name',
        'surname',
        'avatar',
    ]),
    TicketData: new Set([
        'ID',
        'Login',
        'PlaceField',
        'QRPath',
        'Schedule',
        'TransactionDate',
    ]),
    TicketScheduleData: new Set([
        'place',
        'row',
    ]),
};

export default ExtractedFields;
